name: Build APK

on:
  push:
    branches: 
      - main    # Quando um commit for feito na branch 'main', o fluxo será acionado.
      
jobs:
  build:
    runs-on: ubuntu-latest  # Definindo o sistema operacional para o build (Ubuntu)

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Faz o checkout do repositório

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Configurando a versão do Python para a execução do projeto

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git python3-pip openjdk-17-jdk zip unzip libffi-dev python3-dev python3-setuptools libssl-dev
        pip3 install --upgrade Cython buildozer  # Instalando as dependências do Buildozer

    - name: Build APK
      run: |
        buildozer android debug  # Comando para gerar o APK (modo debug)

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: bin/*.apk  # Faz o upload do APK gerado para o GitHub como 'artifact'
