name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Instalar dependências do sistema
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          libffi-dev \
          libssl-dev \
          python3-dev \
          python3-setuptools \
          python3-pip
        pip3 install --upgrade pip
        pip3 install --upgrade Cython buildozer

    - name: Instalar Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-30" \
          "build-tools;30.0.3"

    - name: Build APK com Buildozer
      env:
        ANDROID_HOME: $HOME/android-sdk
        PATH: $HOME/android-sdk/platform-tools:$PATH
      run: |
        buildozer android debug

    - name: Upload APK como artifact
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: bin/*.apk
